apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sample-app
  namespace: test
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: us.gcr.io/techo-gcp-practices/sample-app:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---

kind: Service
apiVersion: v1
metadata:
  name: sample-app
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app
  namespace: test
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 40
